// TIM-1315: Fictional worked examples for each business plan section.
// Summit Street Coffee — Dana Kessler, Flagstaff AZ.
// Source: TIM-1313 content doc. Used as reference UI in the workspace.

import type { BusinessPlanSectionKey } from "./business-plan";

export const SUMMIT_STREET_EXAMPLES: Record<BusinessPlanSectionKey, string> = {
  executive_summary: `Summit Street Coffee will open in downtown Flagstaff, Arizona in March 2027 as a 2,200-square-foot specialty coffee shop serving single-origin espresso drinks, pour-overs, and small-batch baked goods made in-house each morning. The shop will seat 80 guests and operate seven days a week from 6:30 a.m. to 6:00 p.m.

The owner, Dana Kessler, has spent eight years in specialty coffee, the last four as a shift supervisor at Bird Rock Coffee Roasters in Phoenix. She has sourced beans directly from farms in Guatemala and Ethiopia, trained baristas across two locations, and run daily operations for a shop doing $600,000 per year. She is ready to own what she already runs.

Flagstaff has one serious competition gap. The two downtown coffee shops within walking distance of NAU's campus cater to speed and convenience: a Starbucks on Milton and a drive-through espresso chain on Route 66. No shop in the area offers the full specialty experience -- whole-bean brewing protocols, seasonal menus tied to harvest cycles, or counter conversation that turns a first-time visitor into a regular. That gap is Summit Street's market.

The business requires $280,000 to open: $180,000 from an SBA 7(a) loan, $60,000 from Dana's personal savings, and $40,000 from two family investors structured as subordinated debt. At projected revenue of $45,000 per month by month six and $65,000 per month by month twelve, the shop reaches cash-flow breakeven at month eight and retires investor principal within three years.`,

  company_concept: `Summit Street Coffee, LLC will be incorporated in Arizona as a single-member limited liability company in August 2026. The shop will occupy 2,200 square feet at 14 West Summit Avenue, two blocks from Northern Arizona University's main entrance and one block from the downtown transit hub. The space includes a front-of-house with 80 seats, a full espresso bar with four group heads, a brew bar with four pour-over stations, and a production kitchen with commercial oven, proofer, and mixer.

The concept came from an observation Dana made over three years of running a shift at Bird Rock: most coffee shops force a choice between atmosphere and quality. The shops that feel good to sit in serve mediocre espresso. The shops that pull a technically correct shot feel like airport kiosks. Summit Street will not force that choice.

In practice, that means three things. First, the menu will be short: eight espresso drinks, three pour-over options, one cold brew, and one rotating seasonal offering. Every drink is made from beans sourced and approved by Dana personally, roasted by a partner roaster in Tucson. Second, the baked goods will be made in-house each morning by a dedicated baker -- two or three items per day, rotated weekly, nothing from a commissary. Third, the physical space will feel like a room someone actually lives in: mismatched chairs, local art on a rotating display, a long communal table in the center for solo workers and small groups.

The shop will be open seven days a week from 6:30 a.m. to 6:00 p.m. Counter service is the primary model, with one to two staff members circulating tables during peak hours to clear dishes and check on guests. There will be no tableside ordering, no QR menus, and no loyalty app.

Dana's direct involvement in daily operations is not optional and not temporary. She will be behind the bar four to five days a week for the first two years. The shop's quality depends on her being present while the team is trained and the culture is set.`,

  market_analysis: `Flagstaff is a city of 78,000 permanent residents, but that number understates the actual market. Northern Arizona University enrolls approximately 28,000 students, the majority of whom live on or near campus within a 10-minute walk of the proposed Summit Street location. Grand Canyon National Park draws 6 million visitors per year, many of whom pass through Flagstaff as their first or last overnight stop. The city also has a growing remote-work population drawn by its elevation, outdoor recreation, and relative affordability compared to Phoenix and Tucson. Summit Street's core addressable market is the 30,000 to 40,000 people who live, work, or spend meaningful time within a half-mile radius of West Summit Avenue on any given weekday.

The direct competition within that radius is thin. Starbucks on Milton Road serves approximately 400 transactions per day based on Dana's observation count across four weekday visits, but the volume is concentrated in drive-through and mobile order; the cafe seating rarely exceeds half capacity. The drive-through espresso chain on Route 66 has no seating at all. Campus Coffee on Knoles Drive, the only independent shop near campus, opened in 2019 and built its business around iced drinks and sandwich wraps; it does not do pour-overs, does not rotate its bean program, and has not changed its menu since 2021. There is no specialty-forward, sit-down coffee shop in this part of Flagstaff.

The customer opportunity splits into three segments. The first is the Daily Regular: NAU faculty, staff, and upperclassmen who want a consistent, high-quality morning or afternoon coffee and are willing to pay $6 to $8 for a well-made drink. This segment drives predictable weekday revenue and responds to consistency above all else. The second is the Remote Worker who needs reliable wifi, enough seats, and a reason to stay two to three hours; this customer spends $10 to $15 per visit and comes back two to three times per week. The third is the Tourism-Adjacent Visitor -- a couple driving through Flagstaff who wants a good local coffee shop and is willing to spend $20 to $30 on drinks and pastries before continuing their trip. This segment is episodic but high per-visit value.

The specialty coffee category grew at 7.1 percent annually from 2019 to 2024, driven by a consumer preference shift toward quality over convenience. Flagstaff's demographics -- educated, outdoor-oriented, median household income of $48,000 for permanent residents and significantly higher for faculty and the professional class -- match the profile of specialty coffee's strongest buyer segment.

Dana has spoken with six NAU faculty members and four local business owners as informal customer discovery. The consistent feedback: people drive to Tempe or Sedona when they want a serious coffee shop. That trip is the market Summit Street is replacing.`,

  location_real_estate: `Summit Street Coffee is leasing 2,200 square feet at 14 West Summit Avenue in downtown Flagstaff, Arizona. The location sits two blocks from Northern Arizona University's main entrance and one block from the downtown transit hub, placing it directly in the daily path of commuter and student traffic the shop is designed to serve.

The lease term is five years with one five-year renewal option. Base rent is $4,800 per month, or $2.18 per square foot -- below the downtown Flagstaff commercial average of $2.60 to $3.20. The landlord is providing a $30,000 tenant improvement allowance and a two-month rent abatement during construction. Annual rent increases are capped at 3 percent. Dana reviewed the lease with a commercial real estate attorney before signing.

The space was previously occupied by a retail clothing boutique and required full interior demolition. The bones are good: 12-foot ceilings, two ADA-compliant restrooms, a functional HVAC system, and rear alley access for daily dairy and supply deliveries. Electrical service required an upgrade to 200-amp to handle the espresso equipment and commercial kitchen. That upgrade is included in the landlord's improvement allowance.

Three other sites were evaluated before signing. A space on Leroux Street offered more square footage at lower rent but faced a zoning issue around the production kitchen permit. A space on San Francisco Street had the right location but the landlord would not agree to a cap on rent increases. The West Summit Avenue location was the only one that offered the right size, right location, and lease terms worth signing.`,

  buildout_equipment: `The build-out and equipment budget is $157,000. That covers build-out labor and materials beyond the landlord's $30,000 allowance ($62,000), the full equipment package ($95,000), initial inventory and first-month supplies ($18,000), and pre-opening costs including licenses, permits, and soft-launch expenses ($15,000). The operating reserve of $90,000 is budgeted separately.

The espresso program centers on a two-group La Marzocca Linea PB at $18,500, paired with two Mazzer Major grinders -- one for the house espresso blend, one for single-origin pour-over output. The brew bar runs four Kalita Wave 185 stations. Cold brew is produced in-house using a 10-gallon Toddy commercial immersion system cycling a 24-hour batch daily. These are not placeholder equipment choices; they reflect what Dana has used at Bird Rock and what she believes produces consistent results at high volume.

The production kitchen houses a commercial convection oven, a 20-quart stand mixer, a proofing cabinet, and a 6-foot stainless prep table. The baker owns this section of the kitchen from 5:00 a.m. to 10:00 a.m. The kitchen is sized for the opening baked-goods menu -- two pastry variations and one savory item daily -- with room to add a second baker and a second oven in year two if food revenue warrants it.

Major equipment is covered by service contracts: the La Marzocca through Espresso Exchange in Phoenix with quarterly preventive maintenance included, the commercial oven through the manufacturer's extended warranty. Dana has kept a $400 per month reserve in the operating budget for unscheduled service calls.`,

  menu_pricing: `Summit Street's opening menu will have 12 items: eight espresso-based drinks, three brewed single-origin options available by pour-over, and one house cold brew made in-house in 24-hour batches using a 10-gallon immersion system. The menu will not include blended drinks, flavored syrups beyond vanilla and hazelnut, or any tea or matcha program at launch. Those categories might come later; they are not on the opening menu because they take attention and equipment away from what Summit Street actually does well.

The espresso program runs on a two-group La Marzocca Linea PB and a Mazzer grinder. The house espresso blend is sourced from Prism Coffee Works in Tucson, a specialty roaster Dana has worked with since 2021. The pour-over bar offers three single-origin options at any time, rotated seasonally: one natural-process Ethiopian, one washed Central American, and one wildcard chosen by Dana based on what is interesting at the source level during that harvest cycle. Pour-overs are made on Kalita Wave brewers and priced at $7 to $9 depending on the bean's cost.

Pricing reflects what specialty coffee actually costs and the customer segment being served. A standard 12-ounce latte will be $6.50. A 16-ounce cold brew with milk will be $6.00. A pour-over will range from $7.00 to $9.00. A cortado will be $5.25. These prices are at or slightly above the Flagstaff market but below what comparable specialty shops charge in Phoenix and Tucson. The plan is not to apologize for the prices. A small placard near the register will explain the sourcing in two sentences; after that, the product justifies itself.

The food program will be handled by a part-time baker working 20 to 25 hours per week. The daily lineup at opening: two croissant variations (one butter, one seasonal filling), one loaf cake or bar cookie, and one savory item. Items rotate weekly and will be priced from $4.00 to $6.50. Food is projected to account for 18 to 22 percent of total revenue by month six.`,

  marketing_plan: `Summit Street will begin building an audience three months before opening. Dana will document the build-out on Instagram under @summitstreetcoffee, posting two to three times per week: photos of the espresso bar being installed, early test shots from the La Marzocca, introductions to the farmers whose beans will be on the opening menu. The goal on opening day is 400 to 600 followers who feel like they have been watching something get built, not just another coffee shop announce itself.

The opening event will be simple. Dana will invite 40 to 50 people for a private soft-open the night before the public opening: NAU faculty contacts, local business owners, the contractor and his crew, neighbors on Summit Avenue. No press release. No promotional discount. Just a full bar running and a plate of pastries. The people in that room are the word-of-mouth network for the first 60 days.

After opening, the ongoing marketing approach has two parts. The first is operational: be specific enough about what the shop does that the people who love it have something concrete to recommend. "You have to try their Ethiopian pour-over" is a better referral than "it has a really nice vibe." Every staff member will be trained to explain the bean program in two sentences -- not a sales pitch, just enough that a curious customer feels like they learned something. The second part is community presence: one NAU student club sponsorship per semester ($200 to $400 in free drinks), active participation in the downtown merchants association, and a standing 20 percent discount for NAU faculty during off-peak hours. No paid advertising in year one.

Online ordering and a loyalty program are not part of the plan at opening. Dana's experience at Bird Rock was that loyalty apps train customers to chase points rather than develop actual preferences. The goal is to make the shop good enough that people come back because they want to, and bring someone with them. Revenue projections are built on 80 transactions per day in month one growing to 160 by month six, with an average ticket of $10.50.`,

  operations_launch: `Summit Street Coffee's path from lease signing to opening day covers six months and 22 discrete milestones. The sequence reflects what Dana has watched happen at two other build-outs and is adjusted for the specific complexity of this space.

The first three months (August to October 2026) are dedicated to construction, permitting, and equipment procurement. Build-out begins the week the lease is signed. The La Marzocca and Mazzer grinders have 10-week lead times and are being ordered concurrent with the permit application. Failure to have espresso equipment on-site before training starts pushes the opening by two to four weeks, which is why both are in the first purchase cycle.

Training begins in November 2026, six weeks before the projected soft open. Dana will train the Opening-Key Barista to run the bar independently by the end of week two. The baker joins in week three for a three-week test run of the opening baked-goods lineup. By December, every shift has been run at least twice in a simulated full-service environment.

The public opening is planned for the first week of March 2027, preceded by a private soft open for 40 to 50 invited guests in late February. The soft open is a live-fire service with a full bar, the complete opening menu, and real guests. Any service failures during the soft open are corrected before the doors open to the public.`,

  team_hiring: `Dana Kessler, 34, is the founder and will serve as Owner-Operator. She has worked in specialty coffee for eight years. From 2018 to 2022 she worked as a barista and then Lead Barista at Lubbock + Greer Coffee in Phoenix, a single-location independent shop known for its direct-trade sourcing program. In 2022 she joined Bird Rock Coffee Roasters as a Shift Supervisor, managing daily operations at a 1,800-square-foot location doing $550,000 in annual revenue. At Bird Rock she managed a staff of six, oversaw weekly ordering, and was the primary contact for the seasonal bean rotation. She is leaving on good terms; two members of the Bird Rock management team have agreed to serve as informal advisors.

Dana does not have a business degree. She completed a 12-week Entrepreneurship Bootcamp at NAU's College of Business in fall 2025. Her formal financial modeling skills are limited; she has worked since January 2026 with a SCORE mentor, Harriet Odom, a retired regional bank VP with 20 years of commercial lending experience, who reviews Dana's financials monthly at no charge. Dana has also consulted with a Flagstaff commercial real estate attorney on the lease and with a local SBA lender on the loan structure.

The organizational structure at opening will be flat:

- **Owner-Operator (Dana Kessler):** all management, menu decisions, sourcing, and scheduling
- **Opening-Key Barista (to be hired, Q4 2026):** opens the shop four days per week; primary espresso trainer for new hires
- **Baristas x2 (to be hired, Q4 2026):** mid-shift coverage, cleaning, and closing
- **Baker (to be hired, Q4 2026):** 5:00 a.m. to 10:00 a.m. daily; baking and case management
- **Weekend Floater (to be hired, Q1 2027):** added after the first four weeks once weekend rush volume is understood

There are no plans to hire above the Opening-Key Barista in year one. Dana's goal is to build operational knowledge in herself before she delegates it.`,

  financial_plan: `Summit Street will require $280,000 to reach opening day. That total breaks down as: $95,000 for equipment (espresso machine, grinders, brew bar, refrigeration, and production kitchen), $62,000 for build-out and tenant improvements beyond the landlord's $30,000 allowance, $18,000 for initial inventory and the first 30 days of supply, $15,000 for pre-opening marketing and soft-launch costs, and $90,000 held as a six-month operating reserve. The reserve is sized at three times projected month-one cash burn -- not two, which would leave no room for a slower-than-expected ramp.

Funding will come from three sources. The SBA 7(a) loan for $180,000 was submitted to Pinnacle Bank in Flagstaff in March 2026 and is pending approval; Dana has conditional interest and expects a decision by July. The $60,000 personal contribution comes from savings accumulated over eight years. The remaining $40,000 comes from two family investors structured as subordinated debt at 5 percent annual interest with a three-year balloon payment. The family investment carries no equity stake and no board role.

Revenue is projected on a per-transaction model. Month one targets 80 transactions per day at an average ticket of $10.50, producing approximately $24,000 in monthly revenue. Month six targets 160 transactions per day at $10.75, producing approximately $52,000. Month twelve targets 200 transactions per day at $11.00, producing approximately $66,000. These projections were benchmarked against self-reported transaction volume from three comparable independent specialty shops contacted directly by Dana. Summit Street's targets are slightly below their reported month-six and month-twelve averages.

The cost structure at opening: food and beverage COGS at 28 to 32 percent of revenue, payroll at 38 to 42 percent, occupancy at 12 to 14 percent, and all other operating expenses at 8 to 10 percent. Total cost structure in month one is 86 to 98 percent of projected revenue. The shop will not be profitable in month one, and is not expected to be.

The cash-flow breakeven point is projected at month eight. This assumes the revenue ramp tracks within 15 percent of projection through month six. Dana will not draw a salary in months one through three. Beginning in month four she will pay herself $3,200 per month. Her target owner compensation once the shop is stable is $60,000 to $70,000 per year, which she expects to reach by the end of year two if revenue tracks to plan.`,

  funding_request: `Summit Street Coffee is seeking a total of $280,000 to fund the opening. The capital is already partially committed: $60,000 from Dana Kessler's personal savings and $40,000 from two family investors structured as subordinated debt. The remaining $180,000 is being requested as an SBA 7(a) small business loan through Pinnacle Bank in Flagstaff.

The SBA loan application was submitted in March 2026. Dana received conditional interest in April and expects a lending decision by July. The loan is structured with a 10-year amortization at current SBA rates, with principal and interest payments beginning in month four post-closing. The family debt is structured at 5 percent annual interest with a three-year balloon payment, no equity stake, and no operational role for either investor.

The $280,000 covers: equipment at $95,000, build-out beyond the landlord allowance at $62,000, initial inventory and first-month supplies at $18,000, pre-opening marketing and soft-launch costs at $15,000, and a six-month operating reserve at $90,000. The reserve is sized at three times projected month-one cash burn. Dana has reviewed this structure with her SCORE mentor and her SBA lender.

The use of SBA financing rather than outside equity reflects a deliberate decision to retain full ownership. Dana is not opposed to outside investors in principle, but she has seen what happens to coffee shop culture when operators answer to non-operator stakeholders. At this stage, the business is worth funding on debt terms. Equity is a conversation for year three if the business warrants a second location.`,
};
